# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MY_MUSIC', '0002_auto_20170502_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(blank=True, max_length=120, null=True)),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/%d')),
                ('is_favourite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_MUSIC.Album')),
            ],
        ),
    ]
