# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MY_MUSIC', '0003_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
